#!/bin/bash
set -o pipefail

ROOT=$(dirname "${VAR}")
source $HOME/.virtualenv/swap/bin/activate

set -eu

ROOT=$(readlink -f "${ROOT}")
CONFIG=$ROOT/experiment_config.py
echo "Running from $ROOT"
echo $SWAPLOG

# echo "Starting SWAP"
# swap_tools --config-file $ROOT/experiment_config.py randomex --num-golds 1000 10000 1000 --num-trials 20 test1 "Attempting to reproduce previous random plots" --run
# swap_tools --config-file $ROOT/experiment_config.py burnin --num-golds 10000 --gamma 1 50 1 burnin-1 "Testing effects of varying 'gamma' variable" --run
# swap_tools --config-file $CONFIG cvcn --num-golds 5000 --controversial 0 5000 100 --consensus 0 5000 100 cvcn-1 "Testing effects of adding controversial and consensus subjects" --run
# swap_tools

randomex () {
    swap_tools --config-file $CONFIG randomex \
    --num-golds 1000 10000 1000 \
    --num-trials 20 \
    --name randomex-2 --description "Attempting to reproduce previous random plots" \
    --run
}

burnin () {
    swap_tools --config-file $CONFIG burnin \
    --num-golds 10000 \
    --gamma 1 50 1
    --name burnin-2 --description "Testing effects of varying 'gamma' variable" \
    --run
}

cvcn () {
    swap_tools --config-file $CONFIG cvcn \
    --num-golds 2500 \
    --controversial 0 10000 500 \
    --consensus 0 10000 500 \
    --name cvcn-2 --description "Repeating controversial-consensus experiment with proper retirement from limited gold knowledge" \
    --run
}

goldprop () {
    swap_tools --config-file $CONFIG goldprop \
    --num-real 1000 5000 1000 \
    --num-bogus 1000 5000 1000 \
    --num-trials 5 \
    --name golds-2 --description "Testing effects of adding real vs bogus gold labels" \
    --run
}

prior () {
    swap_tools --config-file $CONFIG prior \
    --num-golds 10000 \
    --prior .05 .95 .05 \
    --num-trials 3 \
    --name prior-1 --description "Testing effects of prior" \
    --run
}

echo "Starting SWAP"
run_command=$1

case $run_command in
    "randomex")
        randomex
        ;;
    "burnin")
        burnin
        ;;
    "cvcn")
        cvcn
        ;;
    "goldprop")
        goldprop
        ;;
    "prior")
        prior
        ;;
esac

echo done
